// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// DraftCreateRequest defines model for DraftCreateRequest.
type DraftCreateRequest struct {
	// Content 記事の本文
	Content string `json:"content"`

	// Date 記事の日付
	Date openapi_types.Date `json:"date"`

	// IsPublished 公開状態
	IsPublished *bool `json:"isPublished,omitempty"`

	// Tags 記事に関連するタグ
	Tags []string `json:"tags"`

	// Title ブログ記事のタイトル
	Title string `json:"title"`
}

// DraftCreateResponse defines model for DraftCreateResponse.
type DraftCreateResponse struct {
	// Id 作成された下書きのID
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// PlainError 現状のLambda実装はエラー時にJSONではなくプレーンテキストを返します。
// API Gateway/CloudWatchの運用上はこの形式を正とします。
type PlainError = string

// Post defines model for Post.
type Post struct {
	// Content 記事の本文
	Content *string `json:"content,omitempty"`

	// Date 記事の日付
	Date *openapi_types.Date `json:"date,omitempty"`

	// Id 記事の一意なID
	Id *string `json:"id,omitempty"`

	// IsPublished 公開状態
	IsPublished *bool `json:"isPublished,omitempty"`

	// Tags 記事に関連するタグ
	Tags *[]string `json:"tags,omitempty"`

	// Title ブログ記事のタイトル
	Title *string `json:"title,omitempty"`

	// Ttl Time to live
	Ttl *int `json:"ttl,omitempty"`
}

// PostPublishRequest defines model for PostPublishRequest.
type PostPublishRequest struct {
	// Id 公開する下書きのID
	Id string `json:"id"`

	// IsPublished 公開状態
	IsPublished bool `json:"isPublished"`
}

// PostPublishResponse defines model for PostPublishResponse.
type PostPublishResponse struct {
	// Id 公開された記事のID
	Id *string `json:"id,omitempty"`

	// Message 成功メッセージ
	Message *string `json:"message,omitempty"`
}

// PostDraftsMultipartBody defines parameters for PostDrafts.
type PostDraftsMultipartBody struct {
	Content string             `json:"content"`
	Date    openapi_types.Date `json:"date"`

	// File 添付ファイル（フィールド名は任意だが、代表例として定義）
	File *openapi_types.File `json:"file,omitempty"`

	// IsPublished "true" / "false"（現状は保存時にfalse固定）
	IsPublished *string `json:"isPublished,omitempty"`

	// Tags JSON配列文字列（例: ["Go","AWS"]）
	Tags  string `json:"tags"`
	Title string `json:"title"`
}

// PostDraftsJSONRequestBody defines body for PostDrafts for application/json ContentType.
type PostDraftsJSONRequestBody = DraftCreateRequest

// PostDraftsMultipartRequestBody defines body for PostDrafts for multipart/form-data ContentType.
type PostDraftsMultipartRequestBody PostDraftsMultipartBody

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = PostPublishRequest
