openapi: 3.0.3
info:
  title: ブログ管理API
  description: 下書きおよび公開ブログ記事を管理するためのバックエンドAPI
  version: 1.0.0
servers:
  - url: "{AWS_API_GATEWAY_URL}"
    description: Production API Gateway
    variables:
      AWS_API_GATEWAY_URL:
        default: https://api.example.com
        description: AWS API Gateway URL (フロントエンドプロジェクトの.env.localを参照)

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API Key認証 (AWS_API_GATEWAY_KEY_PROD - フロントエンドプロジェクトの.env.localを参照)

  schemas:
    PlainError:
      type: string
      description: |-
        現状のLambda実装はエラー時にJSONではなくプレーンテキストを返します。
        API Gateway/CloudWatchの運用上はこの形式を正とします。

    Draft:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 下書きの一意なID
          example: 21828f55-1bb6-4a2f-abcc-79e3453f0d8f
        title:
          type: string
          description: ブログ記事のタイトル
          example: Example Post
        date:
          type: string
          format: date
          description: 記事の日付
          example: "2025-08-26"
        content:
          type: string
          description: 記事の本文
          example: This is the content of my first blog post.
        tags:
          type: array
          items:
            type: string
          description: 記事に関連するタグ
          example:
            - Go
            - AWS
            - Lambda
        isPublished:
          type: boolean
          description: 公開状態
          example: false
        ttl:
          type: integer
          description: Time to live (削除時のみ)
          example: 10000000

        attachmentFilePath:
          type: array
          items:
            type: string
          description: S3に保存した添付ファイルのオブジェクトキー一覧（下書き作成時のみ）
          example:
            - 21828f55-1bb6-4a2f-abcc-79e3453f0d8f/example.png

    DraftCreateRequest:
      type: object
      required:
        - title
        - date
        - content
        - tags
      properties:
        title:
          type: string
          description: ブログ記事のタイトル
          example: Example Post
        date:
          type: string
          format: date
          description: 記事の日付
          example: "2025-08-26"
        content:
          type: string
          description: 記事の本文
          example: This is the content of my first blog post.
        tags:
          type: array
          items:
            type: string
          description: 記事に関連するタグ
          example:
            - Go
            - AWS
            - Lambda
        isPublished:
          type: boolean
          description: 公開状態
          example: false

    DraftCreateResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 作成された下書きのID
          example: 21828f55-1bb6-4a2f-abcc-79e3453f0d8f

    Post:
      type: object
      properties:
        id:
          type: string
          description: 記事の一意なID
          example: id1
        title:
          type: string
          description: ブログ記事のタイトル
          example: title
        date:
          type: string
          format: date
          description: 記事の日付
          example: "2025-08-26"
        content:
          type: string
          description: 記事の本文
          example: content
        tags:
          type: array
          items:
            type: string
          description: 記事に関連するタグ
          example:
            - Android Studio
        isPublished:
          type: boolean
          description: 公開状態
          example: false
        ttl:
          type: integer
          description: Time to live
          example: 3600
    PostPublishRequest:
      type: object
      required:
        - id
        - isPublished
      properties:
        id:
          type: string
          description: 公開する下書きのID
          example: id
        isPublished:
          type: boolean
          description: 公開状態
          example: true

    PostPublishResponse:
      type: object
      properties:
        id:
          type: string
          description: 公開された記事のID
          example: id
        message:
          type: string
          description: 成功メッセージ
          example: Blog post published successfully!

    Error:
      type: object
      deprecated: true
      description: |-
        旧仕様。現状のLambda実装はエラー時にJSONではなくプレーンテキストを返すため、
        新規のレスポンス定義では PlainError (string) を使用します。
      properties:
        error:
          type: string
          description: エラーメッセージ
          example: Invalid request body

paths:
  /drafts:
    post:
      summary: 下書きブログデータベースにアイテムを挿入する
      description: 新しい下書きブログ記事を作成します
      tags:
        - Drafts
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DraftCreateRequest"
          multipart/form-data:
            schema:
              type: object
              description: |-
                画像などの添付ファイルを含むフォーム送信。Lambda実装は filename を持つ任意のpartをファイルとしてS3へ保存します。
                tags は JSON配列文字列（例: ["Go","AWS"]）として送信します。
              required:
                - title
                - date
                - content
                - tags
              properties:
                title:
                  type: string
                date:
                  type: string
                  format: date
                content:
                  type: string
                tags:
                  type: string
                  description: 'JSON配列文字列（例: ["Go","AWS"]）'
                isPublished:
                  type: string
                  description: '"true" / "false"（現状は保存時にfalse固定）'
                file:
                  type: string
                  format: binary
                  description: 添付ファイル（フィールド名は任意だが、代表例として定義）
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DraftCreateResponse"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                invalidBody:
                  value: Invalid request body
                unsupportedMediaType:
                  value: Unsupported media type
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                marshalError:
                  value: "Failed to marshal item: {err}"
                dynamoDBError:
                  value: "Failed to put item to DynamoDB: {err}"
                s3Error:
                  value: "Failed to upload file to S3: {err}"

  /drafts/{id}:
    get:
      summary: （現状）IDでアイテムを取得する
      description: |-
        現状のLambda実装は GET_TABLE_NAME 環境変数で指定されたテーブルから id をキーに取得し、
        Post形式のJSONを返します（パスは /drafts/{id} だがレスポンスは Post）。
      tags:
        - Drafts
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 取得する下書きのID
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                missingId:
                  value: Invalid request Body
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                getError:
                  value: アイテムの取得に失敗しました
                parseError:
                  value: アイテムのパースに失敗しました
                responseError:
                  value: レスポンスボディの作成に失敗しました

    delete:
      summary: 下書きブログデータベースから特定のアイテムを削除する
      description: 指定されたIDを持つ下書きブログ記事を削除します
      tags:
        - Drafts
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 削除する下書きのID
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Draft with ID {id} deleted successfully
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                missingId:
                  value: Missing draft ID
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                deleteError:
                  value: "Failed to delete draft: {err}"

  /posts:
    post:
      summary: 下書き用データベースからブログデータベースにアイテムを挿入する
      description: 下書きを本番用ブログデータベースに公開します
      tags:
        - Posts
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPublishRequest"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostPublishResponse"

        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                invalidBody:
                  value: Invalid request body
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                notFound:
                  value: Draft with ID {id} not found
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                getDraftError:
                  value: "Failed to get draft: {err}"
                unmarshalError:
                  value: "Failed to unmarshal draft: {err}"
                marshalError:
                  value: "Failed to marshal post: {err}"
                dynamoDBError:
                  value: "Failed to put post to DynamoDB: {err}"

    get:
      summary: ブログデータベースから全てのアイテムを取得する
      description: |-
        DynamoDBテーブルをScanして全件返します（現状の実装は isPublished=true の絞り込みは行いません）。
      tags:
        - Posts
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                scanError:
                  value: "Failed to scan posts: {err}"
                unmarshalError:
                  value: "Failed to unmarshal posts: {err}"
                marshalError:
                  value: Failed to marshal response

  /posts/{id}:
    get:
      summary: ブログデータベースから特定のアイテムを取得する
      description: 指定されたIDを持つブログ記事を取得します
      tags:
        - Posts
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: 取得する記事のID
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                missingId:
                  value: Invalid request Body
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                notFound:
                  value: 指定された主キーを持つアイテムは見つかりませんでした
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/PlainError"
              examples:
                getError:
                  value: アイテムの取得に失敗しました
                parseError:
                  value: アイテムのパースに失敗しました
                responseError:
                  value: レスポンスボディの作成に失敗しました

tags:
  - name: Drafts
    description: 下書きブログデータベースの操作
  - name: Posts
    description: 本番用ブログデータベースの操作及び、下書きブログデータベースから本番用ブログデータベースへの公開操作
