/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下書きブログデータベースにアイテムを挿入する
         * @description 新しい下書きブログ記事を作成します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DraftCreateRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DraftCreateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "Invalid request body"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drafts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 下書きブログデータベースから特定のアイテムを取得する
         * @description 指定されたIDを持つ下書きブログ記事を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 取得する下書きのID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Draft"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "Missing draft ID"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 下書きブログデータベースから特定のアイテムを削除する
         * @description 指定されたIDを持つ下書きブログ記事を削除します
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 削除する下書きのID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Draft with ID {id} deleted successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "指定された主キーを持つアイテムは見つかりませんでした"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "Failed to delete draft: {err}"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブログデータベースから全てのアイテムを取得する
         * @description 公開されているすべてのブログ記事を取得します
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Post"][];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 下書き用データベースからブログデータベースにアイテムを挿入する
         * @description 下書きを本番用ブログデータベースに公開します
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostPublishRequest"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostPublishResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "Invalid request body"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "error": "Draft with ID {id} not found"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Draft: {
            /**
             * Format: uuid
             * @description 下書きの一意なID
             * @example 21828f55-1bb6-4a2f-abcc-79e3453f0d8f
             */
            id?: string;
            /**
             * @description ブログ記事のタイトル
             * @example Example Post
             */
            title?: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date?: string;
            /**
             * @description 記事の本文
             * @example This is the content of my first blog post.
             */
            content?: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Go",
             *       "AWS",
             *       "Lambda"
             *     ]
             */
            tags?: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished?: boolean;
            /**
             * @description Time to live (削除時のみ)
             * @example 10000000
             */
            ttl?: number;
        };
        DraftCreateRequest: {
            /**
             * @description ブログ記事のタイトル
             * @example Example Post
             */
            title: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date: string;
            /**
             * @description 記事の本文
             * @example This is the content of my first blog post.
             */
            content: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Go",
             *       "AWS",
             *       "Lambda"
             *     ]
             */
            tags: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished: boolean;
        };
        DraftCreateResponse: {
            /**
             * Format: uuid
             * @description 作成された下書きのID
             * @example 21828f55-1bb6-4a2f-abcc-79e3453f0d8f
             */
            id?: string;
        };
        Post: {
            /**
             * @description 記事の一意なID
             * @example id1
             */
            id?: string;
            /**
             * @description ブログ記事のタイトル
             * @example title
             */
            title?: string;
            /**
             * Format: date
             * @description 記事の日付
             * @example 2025-08-26
             */
            date?: string;
            /**
             * @description 記事の本文
             * @example content
             */
            content?: string;
            /**
             * @description 記事に関連するタグ
             * @example [
             *       "Android Studio"
             *     ]
             */
            tags?: string[];
            /**
             * @description 公開状態
             * @example false
             */
            isPublished?: boolean;
            /**
             * @description Time to live
             * @example 3600
             */
            ttl?: number;
        };
        PostPublishRequest: {
            /**
             * @description 公開する下書きのID
             * @example id
             */
            id: string;
            /**
             * @description 公開状態
             * @example true
             */
            isPublished: boolean;
        };
        PostPublishResponse: {
            /**
             * @description 公開された記事のID
             * @example id
             */
            id?: string;
            /**
             * @description 成功メッセージ
             * @example Blog post published successfully!
             */
            message?: string;
        };
        Error: {
            /**
             * @description エラーメッセージ
             * @example Invalid request body
             */
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
